openapi: 3.0.3
info:
  title: FactSet Capital Structure Report Builder API
  description: ''
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  version: 1.0.0
servers:
  - url: https://api.factset.com/report/capital/v1
externalDocs:
  description: Read more about STACH 2.0's row organized schema
  url: https://factset.github.io/stachschema/#/v2/RowOrganized
tags:
  - name: Capital Structure
paths:
  /dcs-detail:
    get:
      tags:
        - - - - Capital Structure
      operationId: getDcsDetail
      summary: Debt Capital Structure (DCS)
      parameters:
        - name: id
          in: query
          description: Company ticker
          required: true
          schema:
            type: string
            example: FDS
        - name: schema
          in: query
          description: >
            The schema that the data is returned as. The following are
            descriptions for the accepted values:

            - table_group_level - STACH 2.0 row organized package format with
            parent-child relationships represented using STACH group level cell
            metadata

            - table_parent_child_columns - STACH 2.0 row organized package
            format with parent-child relationships represented using STACH
            parent-child columns
          required: false
          schema:
            type: string
            enum:
              - table_group_level
              - table_parent_child_columns
            default: table_parent_child_columns
      responses:
        '200':
          $ref: '#/components/responses/200OKStach'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
        '404':
          $ref: '#/components/responses/404NotFound'
        '429':
          $ref: '#/components/responses/429TooManyRequests'
        '500':
          $ref: '#/components/responses/500InternalServerError'
        '503':
          $ref: '#/components/responses/503ServiceUnavailable'
  /source-of-capital:
    get:
      tags:
        - - - - Capital Structure
      operationId: getSourceOfCapital
      summary: Source of Capital
      parameters:
        - name: id
          in: query
          description: Company ticker
          required: true
          schema:
            type: string
            example: FDS
      responses:
        '200':
          $ref: '#/components/responses/200OKStachSourceOfCapital'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
        '404':
          $ref: '#/components/responses/404NotFound'
        '429':
          $ref: '#/components/responses/429TooManyRequests'
        '500':
          $ref: '#/components/responses/500InternalServerError'
        '503':
          $ref: '#/components/responses/503ServiceUnavailable'
  /dcs-summary:
    get:
      tags:
        - - - - Capital Structure
      operationId: getDcsSummary
      summary: Debt Capital Structure (DCS) Summary
      parameters:
        - name: id
          in: query
          description: Company ticker
          required: true
          schema:
            type: string
            example: FDS
        - name: schema
          in: query
          description: >
            The schema that the data is returned as. The following are
            descriptions for the accepted values:

            - table_group_level - STACH 2.0 row organized package format with
            parent-child relationships represented using STACH group level cell
            metadata

            - table_parent_child_columns - STACH 2.0 row organized package
            format with parent-child relationships represented using STACH
            parent-child columns
          required: false
          schema:
            type: string
            enum:
              - table_group_level
              - table_parent_child_columns
            default: table_parent_child_columns
      responses:
        '200':
          $ref: '#/components/responses/200OKStachDcsSummary'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
        '404':
          $ref: '#/components/responses/404NotFound'
        '429':
          $ref: '#/components/responses/429TooManyRequests'
        '500':
          $ref: '#/components/responses/500InternalServerError'
        '503':
          $ref: '#/components/responses/503ServiceUnavailable'
security:
  - basicAuth: []
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
  responses:
    200OKStach:
      description: >-
        Expected response; returns JSON data containing STACH 2.0 row organized
        package format
      headers:
        X-DataDirect-Request-Key:
          schema:
            type: string
          description: FactSet request ID
        Api-Supported-Versions:
          schema:
            type: string
          description: Supported API major versions
        Api-Version:
          schema:
            type: string
          description: API version (semantic versioning)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Response'
          examples:
            groupLevelResponse:
              $ref: '#/components/examples/groupLevelResponse'
            parentChildColumnsResponse:
              $ref: '#/components/examples/parentChildColumnsResponse'
    200OKStachSourceOfCapital:
      description: >-
        Expected response; returns JSON data containing STACH 2.0 row organized
        package format
      headers:
        X-DataDirect-Request-Key:
          schema:
            type: string
          description: FactSet request ID
        Api-Supported-Versions:
          schema:
            type: string
          description: Supported API major versions
        Api-Version:
          schema:
            type: string
          description: API version (semantic versioning)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Response'
          examples:
            sourceOfCapitalResponse:
              $ref: '#/components/examples/sourceOfCapitalResponse'
    200OKStachDcsSummary:
      description: >-
        Expected response; returns JSON data containing STACH 2.0 row organized
        package format
      headers:
        X-DataDirect-Request-Key:
          schema:
            type: string
          description: FactSet request ID
        Api-Supported-Versions:
          schema:
            type: string
          description: Supported API major versions
        Api-Version:
          schema:
            type: string
          description: API version (semantic versioning)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Response'
          examples:
            groupLevelResponse:
              $ref: '#/components/examples/groupLevelResponseDcsSummary'
            parentChildColumnsResponse:
              $ref: '#/components/examples/parentChildColumnsResponseDcsSummary'
    400BadRequest:
      description: >-
        Bad Request. For further assistance, file an issue under "Workflow &
        Throttling - 400 or 429 Response" using `Report Issue` at the top of
        this page, including the X-DataDirect-Request-Key from the header to
        assist in troubleshooting.
      headers:
        X-DataDirect-Request-Key:
          schema:
            type: string
          description: FactSet request ID
        Api-Supported-Versions:
          schema:
            type: string
          description: Supported API major versions
        Api-Version:
          schema:
            type: string
          description: API version (semantic versioning)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            idRequiredParameterError:
              $ref: '#/components/examples/idRequiredParameterError'
            idInvalidParameterError:
              $ref: '#/components/examples/idInvalidParameterError'
            schemaInvalidParameterError:
              $ref: '#/components/examples/schemaInvalidParameterError'
    401Unauthorized:
      description: >-
        Missing or invalid authentication. Ensure you are logged in and have
        successfully generated an API KEY for the IP range you are connecting
        from. For further assistance, file an issue under "Connectivty - 401 or
        403 Responses" using `Report Issue` at the top of this page, including
        the X-DataDirect-Request-Key from the header to assist in
        troubleshooting.
      headers:
        X-DataDirect-Request-Key:
          schema:
            type: string
          description: FactSet request ID
    403Forbidden:
      description: >-
        User is forbidden access with current credentials. Reach out to your
        local FactSet Account Manager for assistance, or file an issue under
        "Connectivty - 401 or 403 Responses" using `Report Issue` at the top of
        this page, including the X-DataDirect-Request-Key from the header to
        assist in troubleshooting.
      headers:
        X-DataDirect-Request-Key:
          schema:
            type: string
          description: FactSet request ID
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            notAuthorized:
              $ref: '#/components/examples/notAuthorized'
    404NotFound:
      description: >-
        Not found. For further assistance, file an issue under "Performance -
        404 and 500 Responses" using `Report Issue` at the top of this page,
        including the X-DataDirect-Request-Key from the header to assist in
        troubleshooting.
      headers:
        X-DataDirect-Request-Key:
          schema:
            type: string
          description: FactSet request ID
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            endpointNotFound:
              $ref: '#/components/examples/endpointNotFound'
    429TooManyRequests:
      description: >-
        Too many requests - this API is rate-limited to 20 requests per second.
        For further assistance, file an issue under "Workflow & Throttling - 400
        or 429 Response" using `Report Issue` at the top of this page, including
        the X-DataDirect-Request-Key from the header to assist in
        troubleshooting.
      headers:
        X-DataDirect-Request-Key:
          schema:
            type: string
          description: FactSet request ID
    500InternalServerError:
      description: >-
        Server error. For further assistance, file an issue under "Performance -
        404 and 500 Responses" using `Report Issue` at the top of this page,
        including the X-DataDirect-Request-Key from the header to assist in
        troubleshooting.
      headers:
        X-DataDirect-Request-Key:
          schema:
            type: string
          description: FactSet request ID
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            genericServerError:
              $ref: '#/components/examples/genericServerError'
    503ServiceUnavailable:
      description: >-
        Service unavailable. Typically a timeout, or result of a rejected
        request to prevent service overload. For further assistance, file an
        issue under "Performance - 404 and 500 Responses" using `Report Issue`
        at the top of this page, including the X-DataDirect-Request-Key from the
        header to assist in troubleshooting.
      headers:
        X-DataDirect-Request-Key:
          schema:
            type: string
          description: FactSet request ID
  examples:
    parentChildColumnsResponse:
      summary: (sample table parent child columns response)
      description: >-
        Subset of rows and columns for an example STACH 2.0 row organized table
        with parent-child columns
      value:
        data:
          version: '2.0'
          tables:
            main:
              headersDefinition:
                columns:
                  - id: detailTableHeader
                    type: string
                    isDimension: true
              definition:
                columns:
                  - id: description1
                    type: string
                    isDimension: true
                  - id: description2
                    type: string
                    isDimension: true
                    parentId: description1
                  - id: description3
                    type: string
                    isDimension: true
                    parentId: description2
                  - id: instrumentID
                    type: string
                  - id: balanceSheetAmountOutstanding
                    type: real
                  - id: currentAmountOutstanding
                    type: real
                  - id: couponRate
                    type: real
                  - id: couponType
                    type: string
                  - id: issueDate
                    type: string
                  - id: maturityDate
                    type: string
                  - id: issueCurrency
                    type: string
                  - id: seniority
                    type: string
                  - id: price
                    type: real
                  - id: ytw
                    type: real
                  - id: oas
                    type: real
              data:
                rows:
                  - rowType: Header
                    cells:
                      - Description
                      - null
                      - null
                      - Instrument ID
                      - Balance Sheet Amount Outstanding
                      - Current Amount Outstanding
                      - Coupon Rate
                      - Coupon Type
                      - Issue Date
                      - Maturity Date
                      - Issue Currency
                      - Seniority
                      - Price
                      - YTW (Yield to Worst)
                      - OAS (LIBOR)
                    headerCellDetails:
                      '0':
                        source: HEADERS
                        columnIndex: 0
                      '1':
                        source: PRIMARY
                        columnIndex: 1
                      '2':
                        source: PRIMARY
                        columnIndex: 2
                      '3':
                        source: HEADERS
                        columnIndex: 0
                      '4':
                        source: HEADERS
                        columnIndex: 0
                      '5':
                        source: HEADERS
                        columnIndex: 0
                      '6':
                        source: HEADERS
                        columnIndex: 0
                      '7':
                        source: HEADERS
                        columnIndex: 0
                      '8':
                        source: HEADERS
                        columnIndex: 0
                      '9':
                        source: HEADERS
                        columnIndex: 0
                      '10':
                        source: HEADERS
                        columnIndex: 0
                      '11':
                        source: HEADERS
                        columnIndex: 0
                      '12':
                        source: HEADERS
                        columnIndex: 0
                      '13':
                        source: HEADERS
                        columnIndex: 0
                      '14':
                        source: HEADERS
                        columnIndex: 0
                  - cells:
                      - Notes/Bonds
                      - null
                      - null
                      - null
                      - 47848
                      - 47848
                      - null
                      - null
                      - null
                      - null
                      - null
                      - null
                      - null
                      - null
                      - null
                  - cells:
                      - Notes/Bonds
                      - Industrial Development Revenue Bonds
                      - null
                      - DCS8073841
                      - 2461
                      - 2461
                      - 1.388
                      - null
                      - null
                      - 12/2051
                      - USD
                      - SNR Sec
                      - null
                      - null
                      - null
                    rowMetadata:
                      interimAmtOutChg:
                        value: true
                  - cells:
                      - Notes/Bonds
                      - Mobil Corp
                      - null
                      - 607059AT9
                      - 250
                      - 250
                      - 8.625
                      - Fixed
                      - 08/1991
                      - 08/2021
                      - USD
                      - SNR Unsec
                      - 105.37265
                      - 0.34193928774702
                      - 13.6422446732113
                columnMetadata:
                  balanceSheetAmountOutstanding:
                    items:
                      currencyCode:
                        value: USD
                      scale:
                        value: 6
                  currentAmountOutstanding:
                    items:
                      currencyCode:
                        value: USD
                      scale:
                        value: 6
                  price:
                    items:
                      currencyCode:
                        value: USD
                  couponRate:
                    items:
                      valueType:
                        value: PERCENTAGE
                  ytw:
                    items:
                      valueType:
                        value: PERCENTAGE
                  oas:
                    items:
                      valueType:
                        value: PERCENTAGE
        meta:
          requestId: 002Q0G-E
          fsymId: QG1HR7-R
          schema: table_parent_child_columns
    groupLevelResponse:
      summary: (sample table group level columns response)
      description: Subset of rows and columns for an example response
      value:
        data:
          version: '2.0'
          tables:
            main:
              headersDefinition:
                columns:
                  - id: detailTableHeader
                    type: string
                    isDimension: true
              definition:
                columns:
                  - id: description
                    type: string
                    isDimension: true
                  - id: instrumentID
                    type: string
                  - id: balanceSheetAmountOutstanding
                    type: real
                  - id: currentAmountOutstanding
                    type: real
                  - id: couponRate
                    type: real
                  - id: couponType
                    type: string
                  - id: issueDate
                    type: string
                  - id: maturityDate
                    type: string
                  - id: issueCurrency
                    type: string
                  - id: seniority
                    type: string
                  - id: price
                    type: real
                  - id: ytw
                    type: real
                  - id: oas
                    type: real
              data:
                rows:
                  - rowType: Header
                    cells:
                      - Description
                      - Instrument ID
                      - Balance Sheet Amount Outstanding
                      - Current Amount Outstanding
                      - Coupon Rate
                      - Coupon Type
                      - Issue Date
                      - Maturity Date
                      - Issue Currency
                      - Seniority
                      - Price
                      - YTW (Yield to Worst)
                      - OAS (LIBOR)
                    headerCellDetails:
                      '0':
                        source: HEADERS
                        columnIndex: 0
                      '1':
                        source: HEADERS
                        columnIndex: 0
                      '2':
                        source: HEADERS
                        columnIndex: 0
                      '3':
                        source: HEADERS
                        columnIndex: 0
                      '4':
                        source: HEADERS
                        columnIndex: 0
                      '5':
                        source: HEADERS
                        columnIndex: 0
                      '6':
                        source: HEADERS
                        columnIndex: 0
                      '7':
                        source: HEADERS
                        columnIndex: 0
                      '8':
                        source: HEADERS
                        columnIndex: 0
                      '9':
                        source: HEADERS
                        columnIndex: 0
                      '10':
                        source: HEADERS
                        columnIndex: 0
                      '11':
                        source: HEADERS
                        columnIndex: 0
                      '12':
                        source: HEADERS
                        columnIndex: 0
                  - cells:
                      - Notes/Bonds
                      - null
                      - 47848
                      - 47848
                      - null
                      - null
                      - null
                      - null
                      - null
                      - null
                      - null
                      - null
                      - null
                    cellDetails:
                      '0':
                        groupLevel: 0
                  - cells:
                      - Industrial Development Revenue Bonds
                      - DCS8073841
                      - 2461
                      - 2461
                      - 1.388
                      - null
                      - null
                      - 12/2051
                      - USD
                      - SNR Sec
                      - null
                      - null
                      - null
                    cellDetails:
                      '0':
                        groupLevel: 1
                  - cells:
                      - Mobil Corp
                      - 607059AT9
                      - 250
                      - 250
                      - 8.625
                      - Fixed
                      - 08/1991
                      - 08/2021
                      - USD
                      - SNR Unsec
                      - 104.388
                      - 0.462109129944423
                      - 28.7109583146608
                    cellDetails:
                      '0':
                        groupLevel: 1
                columnMetadata:
                  balanceSheetAmountOutstanding:
                    items:
                      currencyCode:
                        value: USD
                      scale:
                        value: 6
                  currentAmountOutstanding:
                    items:
                      currencyCode:
                        value: USD
                      scale:
                        value: 6
                  price:
                    items:
                      currencyCode:
                        value: USD
                  couponRate:
                    items:
                      valueType:
                        value: PERCENTAGE
                  ytw:
                    items:
                      valueType:
                        value: PERCENTAGE
                  oas:
                    items:
                      valueType:
                        value: PERCENTAGE
        meta:
          requestId: 002Q0G-E
          fsymId: QG1HR7-R
          schema: table_group_level
    sourceOfCapitalResponse:
      summary: (sample source of capital response)
      description: sample source of capital response
      value:
        data:
          version: '2.0'
        tables:
          main:
            headersDefinition:
              columns:
                - id: sourceOfCapitalTableHeader
                  type: string
                  isDimension: true
            definition:
              columns:
                - id: closeDate
                  type: string
                - id: amountRaised
                  type: real
                - id: description
                  type: string
                - id: issueCurrency
                  type: string
                - id: dealType
                  type: string
                - id: securityType
                  type: string
                - id: offerPrice
                  type: real
                - id: useOfProceeds
                  type: string
            data:
              rows:
                - rowType: Header
                  cells:
                    - Close Date
                    - Amount Raised (USD)
                    - Description
                    - Issue Currency
                    - Deal Type
                    - Security Type
                    - Offer Price
                    - Use Of Proceeds
                  headerCellDetails:
                    '0':
                      source: HEADERS
                      columnIndex: 0
                    '1':
                      source: HEADERS
                      columnIndex: 0
                    '2':
                      source: HEADERS
                      columnIndex: 0
                    '3':
                      source: HEADERS
                      columnIndex: 0
                    '4':
                      source: HEADERS
                      columnIndex: 0
                    '5':
                      source: HEADERS
                      columnIndex: 0
                    '6':
                      source: HEADERS
                      columnIndex: 0
                    '7':
                      source: HEADERS
                      columnIndex: 0
                - cells:
                    - 30 Apr '21
                    - 1545.305
                    - Surgery Center Holdings, Inc. 31 Aug 2026
                    - USD
                    - Debt
                    - Term Loan
                    - null
                    - >-
                      Mergers & Acquisitions, Bank Debt Retirement, Fee &
                      Expense Payment
                - cells:
                    - 19 Mar '21
                    - 305
                    - Spa Holdings 3 Oy 4.88% 04 Feb 2028
                    - USD
                    - Debt
                    - 144A  Bond/Note
                    - 100
                    - Bank Debt Retirement/Refinance
                - cellDetails:
                    '6':
                      cellMetadata:
                        valueType:
                          value: PERCENTAGE
                - cells:
                    - 19 Mar '21
                    - 416.832
                    - Spa Holdings 3 Oy 3.62% 04 Feb 2028
                    - EUR
                    - Debt
                    - 144A  Bond/Note
                    - 100
                    - Bank Debt Retirement/Refinance
              tableMetadata:
                currencyCode:
                  value: USD
        meta:
          requestId: 002Q0G-E
          fsymId: null
    parentChildColumnsResponseDcsSummary:
      summary: (sample table parent child columns response)
      description: >-
        Subset of rows and columns for an example STACH 2.0 row organized table
        with parent-child columns
      value:
        data:
          version: '2.0'
          tables:
            main:
              headersDefinition:
                columns:
                  - id: detailTableHeader
                    type: string
                    isDimension: true
              definition:
                columns:
                  - id: description1
                    type: string
                    isDimension: true
                  - id: description2
                    type: string
                    isDimension: true
                    parentId: description1
                  - id: description3
                    type: string
                    isDimension: true
                    parentId: description2
                  - id: latest
                    type: real
                  - id: latestToLtmEbitda
                    type: real
                  - id: latestToNtmEbitda
                    type: real
                  - id: last
                    type: real
                  - id: lastToLtmEbitda
                    type: real
                  - id: lastToNtmEbitda
                    type: real
              data:
                rows:
                  - cells:
                      - null
                      - null
                      - null
                      - May '21
                      - /LTM EBITDA
                      - /NTM EBITDA
                      - Feb '21
                      - /LTM EBITDA
                      - /NTM EBITDA
                    headerCellDetails:
                      '0':
                        source: HEADERS
                        columnIndex: 0
                      '1':
                        source: HEADERS
                        columnIndex: 0
                      '2':
                        source: HEADERS
                        columnIndex: 0
                      '3':
                        source: HEADERS
                        columnIndex: 0
                      '4':
                        source: HEADERS
                        columnIndex: 0
                      '5':
                        source: HEADERS
                        columnIndex: 0
                      '6':
                        source: HEADERS
                        columnIndex: 0
                  - cells:
                      - Short Term Debt
                      - null
                      - null
                      - null
                      - null
                      - null
                      - null
                      - null
                      - null
                  - cells:
                      - Long Term Debt
                      - null
                      - null
                      - 574.49
                      - 1.02130103038535
                      - 0.998906313302117
                      - 574.399
                      - 1.03639663892232
                      - 1.01769506195566
                  - cells:
                      - Long Term Debt
                      - Revolving Credit
                      - null
                      - 575
                      - 1.02220768415738
                      - 0.9997930863004
                      - 575
                      - 1.03748103214026
                      - 1.01875988750765
                  - cells:
                      - Long Term Debt
                      - Revolving Credit
                      - Unsec. Rev. Facility
                      - 575
                      - null
                      - null
                      - 575
                      - null
                      - null
                  - cells:
                      - Long Term Debt
                      - Term Loans
                      - null
                      - null
                      - null
                      - null
                      - null
                      - null
                      - null
                  - cells:
                      - Long Term Debt
                      - Notes/Bonds
                      - null
                      - null
                      - null
                      - null
                      - null
                      - null
                      - null
                  - cells:
                      - Long Term Debt
                      - Other
                      - null
                      - -0.51
                      - -0.000906653772035242
                      - -0.000886772998283833
                      - -0.601
                      - -0.00108439321794139
                      - -0.00106482555198625
                  - cells:
                      - Long Term Debt
                      - Other
                      - Adjustments
                      - -0.51
                      - null
                      - null
                      - -0.601
                      - null
                      - null
                  - cells:
                      - Long Term Debt, Less Current Portion
                      - null
                      - null
                      - 574.49
                      - 1.02130103038535
                      - 0.998906313302117
                      - 574.399
                      - 1.03639663892232
                      - 1.01769506195566
                  - cells:
                      - Long Term Debt, Less Current Portion
                      - Long Term Debt
                      - null
                      - 574.49
                      - 1.02130103038535
                      - 0.998906313302117
                      - 574.399
                      - 1.03639663892232
                      - 1.01769506195566
                  - cells:
                      - Long Term Debt, Less Current Portion
                      - Current Portion of LTD
                      - null
                      - null
                      - null
                      - null
                      - null
                      - null
                      - null
                  - cells:
                      - Total Debt
                      - null
                      - null
                      - 574.49
                      - 1.02130103038535
                      - 0.998906313302117
                      - 574.399
                      - 1.03639663892232
                      - 1.01769506195566
                columnMetadata:
                  latest:
                    items:
                      scale:
                        value: 6
                  latestToLtmEbitda:
                    items:
                      valueType:
                        value: RATIO
                  last:
                    items:
                      scale:
                        value: 6
                  latestToNtmEbitda:
                    items:
                      valueType:
                        value: RATIO
                  lastToLtmEbitda:
                    items:
                      valueType:
                        value: RATIO
                  lastToNtmEbitda:
                    items:
                      valueType:
                        value: RATIO
        meta:
          requestId: FDS
          fsymId: SQFMK3-R
          schema: table_parent_child_columns
    groupLevelResponseDcsSummary:
      summary: (sample table group level columns response)
      description: Subset of rows and columns for an example response
      value:
        data:
          version: '2.0'
          tables:
            main:
              headersDefinition:
                columns:
                  - id: detailTableHeader
                    type: string
                    isDimension: true
              definition:
                columns:
                  - id: debtClass
                    type: string
                  - id: latest
                    type: real
                  - id: latestToLtmEbitda
                    type: real
                  - id: latestToNtmEbitda
                    type: real
                  - id: last
                    type: real
                  - id: lastToLtmEbitda
                    type: real
                  - id: lastToNtmEbitda
                    type: real
              data:
                rows:
                  - cells:
                      - null
                      - May '21
                      - /LTM EBITDA
                      - /NTM EBITDA
                      - Feb '21
                      - /LTM EBITDA
                      - /NTM EBITDA
                    headerCellDetails:
                      '0':
                        source: HEADERS
                        columnIndex: 0
                      '1':
                        source: HEADERS
                        columnIndex: 0
                      '2':
                        source: HEADERS
                        columnIndex: 0
                      '3':
                        source: HEADERS
                        columnIndex: 0
                      '4':
                        source: HEADERS
                        columnIndex: 0
                      '5':
                        source: HEADERS
                        columnIndex: 0
                      '6':
                        source: HEADERS
                        columnIndex: 0
                  - cells:
                      - Short Term Debt
                      - null
                      - null
                      - null
                      - null
                      - null
                      - null
                    cellDetails:
                      '0':
                        groupLevel: 0
                      '1':
                        groupLevel: 0
                      '2':
                        groupLevel: 0
                      '3':
                        groupLevel: 0
                      '4':
                        groupLevel: 0
                      '5':
                        groupLevel: 0
                      '6':
                        groupLevel: 0
                  - cells:
                      - Long Term Debt
                      - 574.49
                      - 1.02130103038535
                      - 0.998906313302117
                      - 574.399
                      - 1.03639663892232
                      - 1.01769506195566
                    cellDetails:
                      '0':
                        groupLevel: 0
                      '1':
                        groupLevel: 0
                      '2':
                        groupLevel: 0
                      '3':
                        groupLevel: 0
                      '4':
                        groupLevel: 0
                      '5':
                        groupLevel: 0
                      '6':
                        groupLevel: 0
                  - cells:
                      - Revolving Credit
                      - 575
                      - 1.02220768415738
                      - 0.9997930863004
                      - 575
                      - 1.03748103214026
                      - 1.01875988750765
                    cellDetails:
                      '0':
                        groupLevel: 1
                      '1':
                        groupLevel: 0
                      '2':
                        groupLevel: 0
                      '3':
                        groupLevel: 0
                      '4':
                        groupLevel: 0
                      '5':
                        groupLevel: 0
                      '6':
                        groupLevel: 0
                  - cells:
                      - Unsec. Rev. Facility
                      - 575
                      - null
                      - null
                      - 575
                      - null
                      - null
                    cellDetails:
                      '0':
                        groupLevel: 2
                      '1':
                        groupLevel: 0
                      '2':
                        groupLevel: 0
                      '3':
                        groupLevel: 0
                      '4':
                        groupLevel: 0
                      '5':
                        groupLevel: 0
                      '6':
                        groupLevel: 0
                  - cells:
                      - Term Loans
                      - null
                      - null
                      - null
                      - null
                      - null
                      - null
                    cellDetails:
                      '0':
                        groupLevel: 1
                      '1':
                        groupLevel: 0
                      '2':
                        groupLevel: 0
                      '3':
                        groupLevel: 0
                      '4':
                        groupLevel: 0
                      '5':
                        groupLevel: 0
                      '6':
                        groupLevel: 0
                  - cells:
                      - Notes/Bonds
                      - null
                      - null
                      - null
                      - null
                      - null
                      - null
                    cellDetails:
                      '0':
                        groupLevel: 1
                      '1':
                        groupLevel: 0
                      '2':
                        groupLevel: 0
                      '3':
                        groupLevel: 0
                      '4':
                        groupLevel: 0
                      '5':
                        groupLevel: 0
                      '6':
                        groupLevel: 0
                  - cells:
                      - Other
                      - -0.51
                      - -0.000906653772035242
                      - -0.000886772998283833
                      - -0.601
                      - -0.00108439321794139
                      - -0.00106482555198625
                    cellDetails:
                      '0':
                        groupLevel: 1
                      '1':
                        groupLevel: 0
                      '2':
                        groupLevel: 0
                      '3':
                        groupLevel: 0
                      '4':
                        groupLevel: 0
                      '5':
                        groupLevel: 0
                      '6':
                        groupLevel: 0
                  - cells:
                      - Adjustments
                      - -0.51
                      - null
                      - null
                      - -0.601
                      - null
                      - null
                    cellDetails:
                      '0':
                        groupLevel: 2
                      '1':
                        groupLevel: 0
                      '2':
                        groupLevel: 0
                      '3':
                        groupLevel: 0
                      '4':
                        groupLevel: 0
                      '5':
                        groupLevel: 0
                      '6':
                        groupLevel: 0
                  - cells:
                      - Long Term Debt, Less Current Portion
                      - 574.49
                      - 1.02130103038535
                      - 0.998906313302117
                      - 574.399
                      - 1.03639663892232
                      - 1.01769506195566
                    cellDetails:
                      '0':
                        groupLevel: 0
                      '1':
                        groupLevel: 0
                      '2':
                        groupLevel: 0
                      '3':
                        groupLevel: 0
                      '4':
                        groupLevel: 0
                      '5':
                        groupLevel: 0
                      '6':
                        groupLevel: 0
                  - cells:
                      - Long Term Debt
                      - 574.49
                      - 1.02130103038535
                      - 0.998906313302117
                      - 574.399
                      - 1.03639663892232
                      - 1.01769506195566
                    cellDetails:
                      '0':
                        groupLevel: 1
                      '1':
                        groupLevel: 0
                      '2':
                        groupLevel: 0
                      '3':
                        groupLevel: 0
                      '4':
                        groupLevel: 0
                      '5':
                        groupLevel: 0
                      '6':
                        groupLevel: 0
                  - cells:
                      - Current Portion of LTD
                      - null
                      - null
                      - null
                      - null
                      - null
                      - null
                    cellDetails:
                      '0':
                        groupLevel: 1
                      '1':
                        groupLevel: 0
                      '2':
                        groupLevel: 0
                      '3':
                        groupLevel: 0
                      '4':
                        groupLevel: 0
                      '5':
                        groupLevel: 0
                      '6':
                        groupLevel: 0
                  - cells:
                      - Total Debt
                      - 574.49
                      - 1.02130103038535
                      - 0.998906313302117
                      - 574.399
                      - 1.03639663892232
                      - 1.01769506195566
                    cellDetails:
                      '0':
                        groupLevel: 0
                      '1':
                        groupLevel: 0
                      '2':
                        groupLevel: 0
                      '3':
                        groupLevel: 0
                      '4':
                        groupLevel: 0
                      '5':
                        groupLevel: 0
                      '6':
                        groupLevel: 0
                columnMetadata:
                  latest:
                    items:
                      scale:
                        value: 6
                  latestToLtmEbitda:
                    items:
                      valueType:
                        value: RATIO
                  last:
                    items:
                      scale:
                        value: 6
                  latestToNtmEbitda:
                    items:
                      valueType:
                        value: RATIO
                  lastToLtmEbitda:
                    items:
                      valueType:
                        value: RATIO
                  lastToNtmEbitda:
                    items:
                      valueType:
                        value: RATIO
        meta:
          requestId: FDS
          fsymId: SQFMK3-R
          schema: table_group_level
    genericServerError:
      summary: generic server error
      value:
        errors:
          - id: 39314614-e607-465a-ba95-5bb79c362e23
            code: genericServerError
            title: Unexpected error processing request
    endpointNotFound:
      summary: endpoint not found
      value:
        errors:
          - id: 39314614-e607-465a-ba95-5bb79c362e23
            code: endpointNotFound
            title: The requested endpoint does not exist.
    idRequiredParameterError:
      summary: generic parameter error (missing parameter)
      value:
        errors:
          - id: 39314614-e607-465a-ba95-5bb79c362e23
            code: parameterError
            title: 'Missing required parameter(s): ''id'''
    idInvalidParameterError:
      summary: generic parameter error (invalid parameter)
      value:
        errors:
          - id: 39314614-e607-465a-ba95-5bb79c362e23
            code: parameterError
            title: 'Invalid parameter(s): ''id'''
    schemaInvalidParameterError:
      summary: generic parameter error (invalid parameter)
      value:
        errors:
          - id: 39314614-e607-465a-ba95-5bb79c362e23
            code: parameterError
            title: 'Invalid parameter(s): ''schema'''
    notAuthorized:
      summary: not authorized
      value:
        errors:
          - id: 39314614-e607-465a-ba95-5bb79c362e23
            code: notAuthorized
            title: >-
              User is forbidden access with current credentials. For access,
              contact your FactSet sales representative
  schemas:
    ErrorResponse:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorObject'
        meta:
          $ref: '#/components/schemas/Meta'
    ErrorObject:
      type: object
      properties:
        id:
          type: string
        code:
          type: string
        title:
          type: string
        links:
          type: object
          properties:
            about:
              type: string
        detail:
          type: string
        source:
          type: object
          properties:
            parameter:
              type: string
    Meta:
      type: object
      additionalProperties:
        type: string
        nullable: true
    Response:
      type: object
      properties:
        data:
          title: STACH
          description: Returns a STACH 2.0 row organized package
        meta:
          $ref: '#/components/schemas/Meta'
    MetadataEntry:
      type: object
      description: >
        Restricted metadata entries. Restricts the possible key in the following
        STACH schema:

        - RowOrganizedPackage.CellDetail.CellMetadataEntry

        - RowOrganizedPackage.HeaderCellDetail.CellMetadataEntry

        - RowOrganizedPackage.MapOfMetadata.ItemsEntry

        - RowOrganizedPackage.Row.RowMetadataEntry

        - RowOrganizedPackage.TableData.TableMetadataEntry

        And sets restrictions on the possible values for a MetadataItem.
      oneOf:
        - $ref: '#/components/schemas/currencyCode'
        - $ref: '#/components/schemas/currencySymbol'
        - $ref: '#/components/schemas/category'
        - $ref: '#/components/schemas/valueType'
        - $ref: '#/components/schemas/scale'
        - $ref: '#/components/schemas/description'
        - $ref: '#/components/schemas/frequency'
        - $ref: '#/components/schemas/interimStatus'
    interimStatus:
      type: object
      properties:
        interimStatus:
          type: object
          description: >
            classifies the status of each debt issue since last report period.

            - newIssue - New debt issued by the company.

            - newIssueAcq - New debt assumed from an acquisition.

            - matured - Debt that has matured.

            - redeemed - Debt that has been redeemed prior to maturity.

            - terminated - Debt that has been terminated prior to maturity.

            - defaulted - Debt that the issuer has missed interest payment(s) or
            principal.
          properties:
            value:
              type: string
              enum:
                - newIssue
                - newIssueAcq
                - matured
                - redeemed
                - terminated
                - defaulted
    interimAmtOutChg:
      type: object
      properties:
        interimAmtOutChg:
          type: object
          description: >-
            Balance Sheet Amount Outstanding has changed since last report
            period.
          properties:
            value:
              type: boolean
    interimCpnChg:
      type: object
      properties:
        interimCpnChg:
          type: object
          description: Coupon Rate has changed since last report period.
          properties:
            value:
              type: boolean
    interimMatDateChg:
      type: object
      properties:
        interimMatDateChg:
          type: object
          description: Maturity Date has changed since last report period.
          properties:
            value:
              type: boolean
    currencyCode:
      type: object
      properties:
        currencyCode:
          type: object
          description: Code for data currency
          properties:
            value:
              type: string
    currencySymbol:
      type: object
      properties:
        currencySymbol:
          type: object
          description: Symbol for data currency
          properties:
            value:
              type: string
    category:
      type: object
      properties:
        category:
          type: object
          description: >
            Describes data based on source or kind of value

            - ACTUAL - Historical data collected directly from a press release
            or a median consensus from brokers after a report date.

            - ESTIMATE - Forward looking average of broker estimates within a
            specific time horizon.

            - GUIDANCE - Forward looking indication or estimate of future
            performance issued by the company itself.

            - DETAIL - Indicates data that is more granular and may be secondary
            in focus.

            - MAIN - Indicates data is of more impactful or higher importance
            and may want to be emphasized.

            - SECTION - Indicates data that is used in sectioning rows in group
            level STACH format.
          properties:
            value:
              type: string
              enum:
                - ACTUAL
                - ESTIMATE
                - GUIDANCE
                - EXCLUDED
                - CHANGE
                - DETAIL
                - MAIN
                - SECTION
    valueType:
      type: object
      properties:
        valueType:
          type: object
          description: Describes how to interpret numbers
          properties:
            value:
              type: string
              enum:
                - PERCENTAGE
                - RATIO
                - TREND
                - RANGE
    scale:
      type: object
      properties:
        scale:
          type: object
          description: >
            Integer power of 10 to which numbers have been scaled. For example:
            6 implies millions.

            Default is 0.
          properties:
            value:
              type: integer
    description:
      type: object
      properties:
        description:
          type: object
          description: Text describing the data
          properties:
            value:
              type: string
    frequency:
      type: object
      properties:
        frequency:
          type: object
          description: |
            String with frequency of a data series. Allowed values:
            - "D" (daily)
            - "W" (weekly)
            - "AW" (actual weekly)
            - "M" (monthly)
            - "AM" (actual monthly)
            - "Q" (quarterly)
            - "FQ" (fiscal quarterly)
            - "CQ" (calendar quarterly)
            - "AQ" (actual quarterly)
            - "Y" (yearly)
            - "FY" (fiscal yearly)
            - "CY" (calendar yearly)
            - "AY" (actual yearly)
            - "MTD" (month-to-date)
            - "QTD" (quarter-to-date)
            - "YTD" (year-to-date)
            - "FYTD" (fiscal-year-to-date)
            - "CYTD" (calendar-year-to-date)
          properties:
            value:
              type: string
              enum:
                - D
                - W
                - AW
                - M
                - AM
                - Q
                - FQ
                - CQ
                - AQ
                - 'Y'
                - FY
                - CY
                - AY
                - MTD
                - QTD
                - YTD
                - FYTD
                - CYTD
